### PR TITLE
Filtering instead of shifting in  _next

### PR DESCRIPTION
**Pull request by exx8**
This pull request optimized #74 's second example.
This is the last pull request regarding optimizations which is related to shifting.
The request switches shift, which recreate arrays every time by filtering the values once.
This optimization affects mainly on large inputs, but even on small ones, reduction occurs.
The pull request also reduces logic complexity a bit.

This is the final pull request suggested to solve #74 .

### CODE REVIEW

**Comment by suguru03** [comment]
Can you add benchmark? 🙂

**Comment by exx8** [comment]
> Can you add benchmark?
 
Testing it, is a bit more difficult than one might think.
As logic may change the results if it isn't put correctly. I tried to make the minimum test so bench-marking will be stable:




```
const length = 200000;
let rarr=Array.from({length: length}).map(()=>Math.random());

let arr4OldTest=rarr.slice();
it.only('should', function(done) {

  for (let i = 0; i <arr4OldTest.length ; i++)
    if (arr4OldTest[i] < 0.5) {
      if (i == 0)
        arr4OldTest.shift();
      else
        arr4OldTest.splice(i,1);

    i--;
    }
  done();
});

let arr4newTest=rarr.slice()
it.only("should",function(done) {
  const shouldBeDropped=Symbol('this element should be dropped');

  for(let i=0;i<arr4newTest.length;i++)
    if(arr4newTest[i]<0.5)
      arr4newTest[i]=shouldBeDropped;

  const arr2=arr4newTest.filter((value => value!==shouldBeDropped));
  done();
})

```


Results:

old one 2.608s
new one: 13ms.

it seems the old behaves like O(n^2) while the new one behaves like O(n).

**Comment by suguru03** [comment]
I understand your point, but you also need to consider the cost of making a new array, so I would like to see the `queue` benchmark result. 

If it is `queue`, the size of `workersList` depends on `concurrency` and the size of `tasks` is always 1, so both shouldn't be big numbers. (the `payload` in `cargo` shouldn't be a big number as well. )

I roughly wrote a script. In this case, `splice` is faster than making a new array.

```js
function shiftAndSplice(arr, threshold) {
  for (let i = 0; i < arr.length; i++) {
    if (arr[i] >= threshold) {
      continue;
    }
    if (i === 0) {
      arr.shift();
    } else {
      arr.splice(i, 1);
    }
  }
  return arr;
}

const symbol = Symbol('test');

function filter(arr, threshold) {
  for (let i = 0; i < arr.length; i++) {
    if (arr[i] >= threshold) {
      continue;
    }
    arr[i] = symbol;
  }
  return arr.filter(value => value !== symbol);
}

const maxSize = 1000000;
for (let size = 10; size < maxSize; size *= 10) {
  const arr = Array.from({ length: size }).map(() => Math.random());
  for (let t = 0; t < 100; t += 5) {
    const threshold = t * 0.01;
    let start = Date.now();
    for (let i = maxSize / size; i >= 0; i--) {
      shiftAndSplice(arr.slice(), threshold);
    }
    const latency1 = Date.now() - start;
    start = Date.now();
    for (let i = maxSize / size; i >= 0; i--) {
      filter(arr.slice(), threshold);
    }
    const latency2 = Date.now() - start;
    console.log(`size: ${size}\tthreshold: ${t}\tshiftAndSplice: ${latency1}ms\tfilter: ${latency2}ms`);
  }
}```

**Comment by exx8** [comment]
> ```js
> function shiftAndSplice(arr, threshold) {
>   for (let i = 0; i < arr.length; i++) {
>     if (arr[i] >= threshold) {
>       continue;
>     }
>     if (i === 0) {
>       arr.shift();
>     } else {
>       arr.splice(i, 1);
>     }
>   }
>   return arr;
> }
> 
> const symbol = Symbol('test');
> 
> function filter(arr, threshold) {
>   for (let i = 0; i < arr.length; i++) {
>     if (arr[i] >= threshold) {
>       continue;
>     }
>     arr[i] = symbol;
>   }
>   return arr.filter(value => value !== symbol);
> }
> 
> const maxSize = 1000000;
> for (let size = 10; size < maxSize; size *= 10) {
>   const arr = Array.from({ length: size }).map(() => Math.random());
>   for (let t = 0; t < 100; t += 5) {
>     const threshold = t * 0.01;
>     let start = Date.now();
>     for (let i = maxSize / size; i >= 0; i--) {
>       shiftAndSplice(arr.slice(), threshold);
>     }
>     const latency1 = Date.now() - start;
>     start = Date.now();
>     for (let i = maxSize / size; i >= 0; i--) {
>       filter(arr.slice(), threshold);
>     }
>     const latency2 = Date.now() - start;
>     console.log(`size: ${size}\tthreshold: ${t}\tshiftAndSplice: ${latency1}ms\tfilter: ${latency2}ms`);
>   }
> }`
> ```

I run your code and I had this results:

```
size: 10	threshold: 0	shiftAndSplice: 10ms	filter: 18ms
size: 10	threshold: 5	shiftAndSplice: 15ms	filter: 10ms
size: 10	threshold: 10	shiftAndSplice: 21ms	filter: 58ms
size: 10	threshold: 15	shiftAndSplice: 30ms	filter: 47ms
size: 10	threshold: 20	shiftAndSplice: 11ms	filter: 56ms
size: 10	threshold: 25	shiftAndSplice: 11ms	filter: 46ms
size: 10	threshold: 30	shiftAndSplice: 10ms	filter: 44ms
size: 10	threshold: 35	shiftAndSplice: 21ms	filter: 41ms
size: 10	threshold: 40	shiftAndSplice: 14ms	filter: 51ms
size: 10	threshold: 45	shiftAndSplice: 22ms	filter: 38ms
size: 10	threshold: 50	shiftAndSplice: 20ms	filter: 37ms
size: 10	threshold: 55	shiftAndSplice: 18ms	filter: 38ms
size: 10	threshold: 60	shiftAndSplice: 18ms	filter: 38ms
size: 10	threshold: 65	shiftAndSplice: 24ms	filter: 35ms
size: 10	threshold: 70	shiftAndSplice: 23ms	filter: 35ms
size: 10	threshold: 75	shiftAndSplice: 23ms	filter: 35ms
size: 10	threshold: 80	shiftAndSplice: 23ms	filter: 39ms
size: 10	threshold: 85	shiftAndSplice: 26ms	filter: 35ms
size: 10	threshold: 90	shiftAndSplice: 24ms	filter: 33ms
size: 10	threshold: 95	shiftAndSplice: 22ms	filter: 33ms
size: 100	threshold: 0	shiftAndSplice: 3ms	filter: 24ms
size: 100	threshold: 5	shiftAndSplice: 7ms	filter: 27ms
size: 100	threshold: 10	shiftAndSplice: 26ms	filter: 26ms
size: 100	threshold: 15	shiftAndSplice: 10ms	filter: 26ms
size: 100	threshold: 20	shiftAndSplice: 10ms	filter: 23ms
size: 100	threshold: 25	shiftAndSplice: 12ms	filter: 22ms
size: 100	threshold: 30	shiftAndSplice: 12ms	filter: 25ms
size: 100	threshold: 35	shiftAndSplice: 18ms	filter: 28ms
size: 100	threshold: 40	shiftAndSplice: 19ms	filter: 26ms
size: 100	threshold: 45	shiftAndSplice: 22ms	filter: 25ms
size: 100	threshold: 50	shiftAndSplice: 23ms	filter: 23ms
size: 100	threshold: 55	shiftAndSplice: 25ms	filter: 35ms
size: 100	threshold: 60	shiftAndSplice: 43ms	filter: 24ms
size: 100	threshold: 65	shiftAndSplice: 26ms	filter: 24ms
size: 100	threshold: 70	shiftAndSplice: 27ms	filter: 23ms
size: 100	threshold: 75	shiftAndSplice: 28ms	filter: 25ms
size: 100	threshold: 80	shiftAndSplice: 31ms	filter: 27ms
size: 100	threshold: 85	shiftAndSplice: 31ms	filter: 24ms
size: 100	threshold: 90	shiftAndSplice: 30ms	filter: 24ms
size: 100	threshold: 95	shiftAndSplice: 31ms	filter: 27ms
size: 1000	threshold: 0	shiftAndSplice: 6ms	filter: 40ms
size: 1000	threshold: 5	shiftAndSplice: 9ms	filter: 52ms
size: 1000	threshold: 10	shiftAndSplice: 15ms	filter: 44ms
size: 1000	threshold: 15	shiftAndSplice: 19ms	filter: 42ms
size: 1000	threshold: 20	shiftAndSplice: 24ms	filter: 44ms
size: 1000	threshold: 25	shiftAndSplice: 27ms	filter: 43ms
size: 1000	threshold: 30	shiftAndSplice: 31ms	filter: 46ms
size: 1000	threshold: 35	shiftAndSplice: 35ms	filter: 46ms
size: 1000	threshold: 40	shiftAndSplice: 35ms	filter: 46ms
size: 1000	threshold: 45	shiftAndSplice: 39ms	filter: 48ms
size: 1000	threshold: 50	shiftAndSplice: 42ms	filter: 46ms
size: 1000	threshold: 55	shiftAndSplice: 45ms	filter: 47ms
size: 1000	threshold: 60	shiftAndSplice: 49ms	filter: 46ms
size: 1000	threshold: 65	shiftAndSplice: 49ms	filter: 41ms
size: 1000	threshold: 70	shiftAndSplice: 50ms	filter: 41ms
size: 1000	threshold: 75	shiftAndSplice: 53ms	filter: 40ms
size: 1000	threshold: 80	shiftAndSplice: 52ms	filter: 37ms
size: 1000	threshold: 85	shiftAndSplice: 53ms	filter: 37ms
size: 1000	threshold: 90	shiftAndSplice: 56ms	filter: 36ms
size: 1000	threshold: 95	shiftAndSplice: 56ms	filter: 34ms
size: 10000	threshold: 0	shiftAndSplice: 3ms	filter: 41ms
size: 10000	threshold: 5	shiftAndSplice: 50ms	filter: 44ms
size: 10000	threshold: 10	shiftAndSplice: 92ms	filter: 42ms
size: 10000	threshold: 15	shiftAndSplice: 131ms	filter: 44ms
size: 10000	threshold: 20	shiftAndSplice: 157ms	filter: 44ms
size: 10000	threshold: 25	shiftAndSplice: 189ms	filter: 48ms
size: 10000	threshold: 30	shiftAndSplice: 212ms	filter: 50ms
size: 10000	threshold: 35	shiftAndSplice: 240ms	filter: 46ms
size: 10000	threshold: 40	shiftAndSplice: 253ms	filter: 46ms
size: 10000	threshold: 45	shiftAndSplice: 273ms	filter: 46ms
size: 10000	threshold: 50	shiftAndSplice: 286ms	filter: 45ms
size: 10000	threshold: 55	shiftAndSplice: 292ms	filter: 44ms
size: 10000	threshold: 60	shiftAndSplice: 313ms	filter: 41ms
size: 10000	threshold: 65	shiftAndSplice: 319ms	filter: 40ms
size: 10000	threshold: 70	shiftAndSplice: 334ms	filter: 39ms
size: 10000	threshold: 75	shiftAndSplice: 349ms	filter: 36ms
size: 10000	threshold: 80	shiftAndSplice: 358ms	filter: 35ms
size: 10000	threshold: 85	shiftAndSplice: 368ms	filter: 33ms
size: 10000	threshold: 90	shiftAndSplice: 380ms	filter: 32ms
size: 10000	threshold: 95	shiftAndSplice: 391ms	filter: 30ms
size: 100000	threshold: 0	shiftAndSplice: 4ms	filter: 62ms
size: 100000	threshold: 5	shiftAndSplice: 576ms	filter: 71ms
size: 100000	threshold: 10	shiftAndSplice: 1107ms	filter: 66ms
size: 100000	threshold: 15	shiftAndSplice: 1567ms	filter: 75ms
size: 100000	threshold: 20	shiftAndSplice: 1986ms	filter: 77ms
size: 100000	threshold: 25	shiftAndSplice: 2370ms	filter: 64ms
size: 100000	threshold: 30	shiftAndSplice: 2725ms	filter: 61ms
size: 100000	threshold: 35	shiftAndSplice: 3081ms	filter: 63ms
size: 100000	threshold: 40	shiftAndSplice: 3402ms	filter: 60ms
size: 100000	threshold: 45	shiftAndSplice: 3678ms	filter: 62ms
size: 100000	threshold: 50	shiftAndSplice: 3952ms	filter: 56ms
size: 100000	threshold: 55	shiftAndSplice: 4215ms	filter: 57ms
size: 100000	threshold: 60	shiftAndSplice: 4446ms	filter: 75ms
size: 100000	threshold: 65	shiftAndSplice: 4647ms	filter: 55ms
size: 100000	threshold: 70	shiftAndSplice: 4836ms	filter: 52ms
size: 100000	threshold: 75	shiftAndSplice: 5075ms	filter: 53ms
size: 100000	threshold: 80	shiftAndSplice: 5233ms	filter: 51ms
size: 100000	threshold: 85	shiftAndSplice: 5411ms	filter: 42ms
size: 100000	threshold: 90	shiftAndSplice: 5582ms	filter: 41ms
size: 100000	threshold: 95	shiftAndSplice: 5734ms	filter: 46ms
```

It seems that for small array shift & slice is better while for large ones, filter is better.
I believe that we should consider combining the logics.

**Comment by suguru03** [comment]
Again, `splice` is called only once and `workersList` shouldn't be a big number, so I don't think `filter` would improve performance for `queue`.

I will close this PR for now.

**Pull request closed without merging**
