### PR TITLE
Add queue.remove(testFn)

### PR DESCRIPTION
**Pull request by yles9056**
Add queue.remove(testFn) to Neo-Async v2.4.0
This function is from Async v2.5.0

### CODE REVIEW

**Comment by suguru03** [comment]
@yles9056 Thank you for your PR! :)
Dist files are generated automatically, could you add the feature to [the main file](https://github.com/suguru03/neo-async/blob/master/lib/async.js#L7734-L7785)?  Also if you are able to add these test cases, it would be helpful.

**Comment by yles9056** [comment]
@suguru03 
Sorry, I tried several times, but couldn't get it work.
I added test case for queue.remove() and ran on a test on my computer to make sure everything works.
But it just can't pass the online coverage test when I upload the files. The reason is unknown.

**Comment by suguru03** [comment]
@yles9056 Thank you for adding test cases and fixing it.
Test cases are fine, it is only coverage problem. I'll handle it. 😄

**Comment by yles9056** [comment]
Thanks for the help!

**Pull request merged**
